"""
Shared data models for the RAG guidance pipeline.

All pipeline stages exchange these types. Pydantic models are used for anything
that crosses an API boundary (metadata sent to Vertex AI Search); plain dataclasses
are used for in-process pipeline state.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Metadata (Pydantic — crosses GCP API boundary)
# ---------------------------------------------------------------------------


class ChunkMetadata(BaseModel):
    """Per-chunk metadata generated by Gemini and stored in Vertex AI Search.

    Field names, enums, and defaults mirror ``config/rta_v1.json`` — the ACTIVE
    real-time-analysis (RTA) schema (``ChunkMetadata_v1``, 23 fields). That JSON
    file is the single source of truth for the controlled vocabulary; ingestion
    validates against it via ``config.schema_loader.SchemaVocabulary``. The
    37-field unified RTA+ASA schema in ``config/metadata_schema.json`` is
    retained for future after-session-analysis work and is NOT loaded by the RTA
    ingest path (migrated 2026-07-20).

    Keep this model in sync with ``rta_v1.json``: fields here are serialized to
    ``structData`` (``uploader``) and registered as filterable DataStore
    attributes via ``scripts/setup_vertex_search.py``. Schema changes require a
    purge + full re-import — see the schema ``notes`` block and
    ``config/agentic_document.md``.

    Only ``doc_id`` is strictly required; every other field carries a
    schema-aligned default so that ``_fallback_extraction`` never hard-fails when
    Gemini output is unavailable. ``year_published`` is kept ``Optional`` so the
    model also accepts the nullable form used by the preserved ASA schema.
    """

    # --- Provenance / identity -------------------------------------------
    doc_id: str = Field(description="SHA-256 hex digest of the source PDF bytes")
    source_file: str = Field(default="", description="Original filename (basename only)")
    title: str = Field(default="", description="Inferred document or chapter title")
    chapter: str = Field(default="", description="Nearest chapter/session heading above the chunk")
    page_start: int = Field(default=0, description="First page of chunk (1-indexed)")
    page_end: int = Field(default=0, description="Last page of chunk (1-indexed)")
    chunk_index: int = Field(default=0, description="Sequential index within the document")
    year_published: Optional[int] = Field(
        default=None, description="Publication year; 0/None if not extractable"
    )

    # --- Orientation / classification ------------------------------------
    domain: str = Field(
        default="psychotherapy_general",
        description="Document-level orientation (cognitive_behavioral_therapy, ...)",
    )
    subdomain: str = Field(default="", description="Narrower topic within the domain (free text)")
    doc_type: str = Field(
        default="other",
        description="treatment_manual | textbook | clinical_guideline | other",
    )

    # --- Clinical content (chunk-level) ----------------------------------
    therapeutic_modality: list[str] = Field(
        default_factory=list, description="Therapy modalities this passage addresses (CBT, DBT, MI, ...)"
    )
    clinical_presentation: list[str] = Field(
        default_factory=list, description="Diagnostic themes addressed (depression, trauma, SUD, ...)"
    )
    session_event_tags: list[str] = Field(
        default_factory=lambda: ["none"],
        description="In-session event types this chunk is ABOUT (primary RTA retrieval trigger)",
    )
    session_phase: str = Field(default="any", description="Point in the treatment arc this applies to")

    # --- Directionality / safety (RTA relational contraindication model) --
    directionality: str = Field(
        default="neutral",
        description="indicated | contraindicated | cautionary | neutral. Co-required with applies_when.",
    )
    applies_when: list[str] = Field(
        default_factory=list,
        description="States/events/presentations under which directionality is active (OR semantics)",
    )
    clinical_caution: list[str] = Field(
        default_factory=list, description="Explicit contraindications/precautions stated in the chunk"
    )
    risk_dimension_tags: list[str] = Field(
        default_factory=list, description="Ongoing risk-monitoring dimensions this chunk addresses"
    )

    # --- Techniques / retrieval support ----------------------------------
    technique_tags: list[str] = Field(
        default_factory=list, description="Named clinical techniques (chain analysis, imaginal exposure, ...)"
    )
    keywords: list[str] = Field(default_factory=list, description="Key topic terms extracted by Gemini")

    # --- Population / instruments -----------------------------------------
    patient_population: list[str] = Field(
        default_factory=lambda: ["not_specified"],
        description="Population the chunk's evidence/recommendation applies to (ranking moderator)",
    )
    clinical_measure_tags: list[str] = Field(
        default_factory=list, description="Clinical instruments referenced (PHQ-9, C-SSRS, ...)"
    )


# ---------------------------------------------------------------------------
# Extraction (dataclasses — internal pipeline state)
# ---------------------------------------------------------------------------


@dataclass
class Page:
    """A single extracted page from a PDF."""

    page_num: int
    text: str
    tables: list[dict] = field(default_factory=list)
    # Each table: {"rows": [["cell", ...], ...], "bbox": (x0, y0, x1, y1)}
    has_figures: bool = False


@dataclass
class ExtractedDocument:
    """Complete output of the PDF extraction stage."""

    doc_id: str
    source_file: str
    source_path: str
    pages: list[Page] = field(default_factory=list)
    extraction_method: str = "pdfplumber"  # "pdfplumber" | "document_ai"


# ---------------------------------------------------------------------------
# Chunking
# ---------------------------------------------------------------------------


@dataclass
class Chunk:
    """A single semantically coherent text segment ready for indexing."""

    chunk_id: str           # Canonical form: "{doc_id}_{chunk_index:05d}"
    doc_id: str
    text: str
    page_start: int
    page_end: int
    chunk_index: int
    parent_section: str     # Nearest detected section header above this chunk
    metadata: Optional[ChunkMetadata] = None


# ---------------------------------------------------------------------------
# Retrieval
# ---------------------------------------------------------------------------


@dataclass
class SearchResult:
    """A single result returned by Vertex AI Search."""

    chunk_id: str
    doc_id: str
    text: str
    score: float
    metadata: Optional[ChunkMetadata] = None


# ---------------------------------------------------------------------------
# Generation / Citations
# ---------------------------------------------------------------------------


@dataclass
class Attribution:
    """Maps a span of generated text back to a retrieved source chunk.

    Populated from Vertex AI grounding metadata. The mapping is approximate —
    see caveats.md §2 (Citation Accuracy).
    """

    segment_text: str       # Portion of the generated response this attribution covers
    source_chunk_id: str
    source_doc_id: str
    confidence: float = 1.0


@dataclass
class Citation:
    """A formatted, user-facing citation for a retrieved source."""

    number: int             # [1], [2], ... reference number in the response text
    source_file: str
    title: str
    chapter: str
    page_start: int
    page_end: int
    chunk_id: str


@dataclass
class GeneratedResponse:
    """Final output of the end-to-end RAG pipeline for a single query."""

    text: str                                           # Response with inline [n] citation markers
    citations: list[Citation] = field(default_factory=list)
    attributions: list[Attribution] = field(default_factory=list)
    domain: str = ""
    query: str = ""


# ---------------------------------------------------------------------------
# Operations
# ---------------------------------------------------------------------------


@dataclass
class ImportResult:
    """Result of a Vertex AI Search async import operation."""

    operation_name: str
    success_count: int = 0
    failure_count: int = 0
    errors: list[str] = field(default_factory=list)
    completed: bool = False
